const paintings = [
    { title: "Princesse de Broglie - Jean Auguste Dominique Ingres", url: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/459106/1964622/main-image" },
    { title: "In the Meadow - Auguste Renoir", url: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/437434/795980/main-image" },
    { title: "The Lovers - Rene Magritte", url: "https://upload.wikimedia.org/wikipedia/en/thumb/5/59/Ren%C3%A9_Magritte_-_The_Lovers_%28Les_Amants%29_1928.jpg/960px-Ren%C3%A9_Magritte_-_The_Lovers_%28Les_Amants%29_1928.jpg" },
    { title: "The Love Letter - Jean Honore Fragonard", url: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/436322/1661166/main-image" },
    { title: "The Birth of Venus - Sandro Botticelli", url: "https://www.datocms-assets.com/103094/1688659635-1503909239806647-605174-2.jpg?auto=format%2Ccompress&cs=srgb&dpr=0.5&max-w=400" },
    { title: "Flowers and Fruit in a Chinese Bowl - Juan de Zurbarán", url: "https://www.artic.edu/iiif/2/9e4bfbcc-176f-3dac-4529-f67c9a98065c/full/843,/0/default.jpg" },
    { title: "The Harvesters - Pieter Bruegel the Elder", url:"https://collectionapi.metmuseum.org/api/collection/v1/iiif/435809/794356/main-image" },
    { title: "The Astronomer - Johannes Vermeer", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa5dg3uc-9SepAF8JFnr5qClfKntffw1HsFQ&s" },
    { title: "The  Tower of Babel - Pieter Bruegel the Elder", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg/500px-Pieter_Bruegel_the_Elder_-_The_Tower_of_Babel_%28Vienna%29_-_Google_Art_Project_-_edited.jpg" },
    { title: "Two Sisters (On the Terrace) - Pierre-Auguste Renior", url: "https://www.artic.edu/iiif/2/3a608f55-d76e-fa96-d0b1-0789fbc48f1e/full/1686,/0/default.jpg" },
    { title: "Vue de toits (Effet de neige) - Gustave Caillebotte", url: "https://cdn.mediatheque.epmoo.fr/link/3c9igq/mlg1butmvgumrts.jpg" },
    { title: "Shepherd and Shepherdess Reposing - Francois Boucher", url: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Fran%C3%A7ois_Boucher_-_Shepherd_and_Shepherdess_Reposing_-_WGA02915.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail_unscaled&_=20110609044800" },
    { title: "The Virgin and Child with Saints Jerome and Dominic - Filippino Lippi", url: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Filippino_Lippi_%28c.1457-1504%29_-_The_Virgin_and_Child_with_Saints_Jerome_and_Dominic_-_NG293_-_National_Gallery.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail_unscaled&_=20200704180153" },
    { title: "Flora - Rembrandt (Rembrandt van Rijn)", url: "https://collectionapi.metmuseum.org/api/collection/v1/iiif/437398/794417/main-image" },
    { title: "The Sense of Sight - Annie Louisa Swynnerton", url: "https://annielouisaswynnerton.com/wp-content/uploads/2025/04/the-sense-of-sight-1895-frame.jpg?w=1024" },
    { title: "The Annunciation - Fra Angelico", url: "https://upload.wikimedia.org/wikipedia/commons/8/8f/La_Anunciaci%C3%B3n_de_Fra_Angelico.jpg" },
    { title: "Blind Man's Buff - Adolph von Menzel", url: "https://upload.wikimedia.org/wikipedia/commons/b/bc/Blind_Man%27s_Buff_by_Adolph_von_Menzel%2C_NG_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original" },
    { title: "The Lady of Shalott - John William Waterhouse", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project_edit.jpg/1280px-John_William_Waterhouse_-_The_Lady_of_Shalott_-_Google_Art_Project_edit.jpg" },
    { title: "A Sunday Afternoon on the Island of La Grande Jatte - Georges Seurat", url: "https://upload.wikimedia.org/wikipedia/commons/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg" },
    { title: "Two Men Contemplating the Moon - Caspar David Friedrich", url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLY8qfEeG9QQfewZXjAXJXWUvdnprDcIBJKg&s" }
];

const songs = [
    { embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/0irXFjfMY0YDUpudTgkJef?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' }, //fleeting
    { embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/1c6gAUV7w8g34UIHkUctlS?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' }, //star
    { embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/5m3rVRNkTv5EQnPuF293we?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' }, //death & romance
    { embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/7Azgd4AE9GdoGazLv4Wr0K?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' }, //i wonder
    { embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/10kvU6okNQBJ7gCYo0X5ai?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' }, //on et on
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/77evpfqHmmSklsFpo8wLCB?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>' }, //within you, within me
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/4Z2PtqWOBXJOgQ7UCLO3py?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //dont let the good life pass you by
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/2wjK5rliM6oPiq50R7DNhp?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //changing of the seasons
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/3qs1ozCx271UQqmzC7oNuj?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //the king
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/4BM8yJ0PzBi2ZewpMTOxtx?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //fernando
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/6Yzh272O4hwZHjrnXYhL8a?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //do it, try it
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/3pr0y5h4MkBngy6gyozLDV?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //voodoo
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/3fV4kgcQzh2aLGSJbSAtoV?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //crystal clear
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/4mQtXW0vrHC3oTkA1mQsb0?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //operator
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/6AY1M1akbsVaQN3ATVyzH7?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //hannah hunt
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/6kAOOamDflxqkrAWI6wZRR?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //free
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/2Zd9awmsA8KuF65snhz7YH?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //puzzle pieces
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/7olFqYuOkisFHqudWw4pVZ?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //who you are
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/6Sex737JxUArLplUR9hzPE?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //wait for the moment
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/44ZKnfWEkp7wPs035j4Tua?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //casio
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/30ae9cv36eD4Q6Zc8PVF8v?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //leave it on the dancefloor
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/0S3BtG3i5tkQmehJhIhHF3?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //time
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/1Q34tAtTWI6RdW1qzFQiPb?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //your smiling face
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/0bRXwKfigvpKZUurwqAlEh?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //lovely day
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/4qfsIA030Dnr1K6rs2JVYq?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'}, //turn up the sunshine
    {embed: '<iframe data-testid="embed-iframe" style="border-radius:12px" src="https://open.spotify.com/embed/track/6golelYKuy85o3u0cxIxFK?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'} //the wire

];

function updateDailyContent() {
    const now = new Date();
    const dayOfYear = Math.floor((now - new Date(now.getFullYear(), 0, 0)) / 1000 / 60 / 60 / 24);
    
    // Select items based on the day
    const painting = paintings[dayOfYear % paintings.length];
    const song = songs[dayOfYear % songs.length];

    // Update the UI
    document.getElementById('current-date').innerText = now.toDateString();
    document.getElementById('daily-painting').src = painting.url;
    document.getElementById('painting-title').innerText = painting.title;
    document.getElementById('daily-song').innerHTML = song.embed;
}

updateDailyContent();